version: "3.5"

services:
  test_my_chatbot_db:
    container_name: "localhost:5430"
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
       - /var/lib/postgresql/${POSTGRES_VERSION}/main:/src/postgresql
    ports:
      - "5430:5432"
    networks:
      - default
    restart: always

  test_my_chatbot_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "localhost:3002"
    restart: on-failure
    environment:
      - NODE_ENV=development
    volumes:
       - ${REPO_PATH}:/src
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3002:8080"
    command: bash -c "sequelize db:migrate:undo:all && sequelize db:migrate && sequelize db:seed:all && npm run start"
    networks:
      - default

networks:
  default:
    external:
      name: webproxy
