version: "3.5"

services:
  test_my_chatbot_db_prod:
    container_name: test_my_chatbot_db_prod
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
       - /var/lib/postgresql/10/main:./postgresql
    ports:
      - "5432:5432"
    networks:
      - default
    restart: always

  test_my_chatbot_api_prod:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: test_my_chatbot_api_prod
    restart: on-failure
    volumes:
       - /home/herve/repo/test-my-chatbot-api:/src
    # port make it available outside the container AND server
    ports:
      - "3004:8080"
    command: bash -c "sequelize db:migrate:undo:all && sequelize db:migrate && sequelize db:seed:all && npm run start"
    environment:
      - VIRTUAL_HOST=api.test-my-chatbot.com
      - LETSENCRYPT_HOST=api.test-my-chatbot.com
      - LETSENCRYPT_EMAIL=herve.tchikladze@epitech.eu
      - NODE_ENV=production
    networks:
      - default

networks:
  default:
    external:
      name: webproxy
