version: "3.5"

services:
  test_my_chatbot_db:
    container_name: test_my_chatbot_db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
       - /var/lib/postgresql/10/main:./postgresql
    ports:
      - "5430:5432"
    networks:
      - default
    restart: always

  test_my_chatbot_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_my_chatbot_api
    restart: on-failure
    environment:
      - NODE_ENV=development
    volumes:
       - /home/herve/repo/test-my-chatbot-api:/src
    # port make it available outside the container AND server
    ports:
      - "3002:8080"
    command: bash -c "sequelize db:migrate:undo:all && sequelize db:migrate && sequelize db:seed:all && npm run start"
    networks:
      - default

networks:
  default:
    external:
      name: webproxy
