FROM node:12-slim
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# NECESSARY TO LOAD NODE-SASS MODULE
RUN apt-get update -y && apt-get install build-essential python -y

# INSTALL DOCKER
RUN  apt-get install \
     apt-transport-https \
     ca-certificates \
     curl \
     software-properties-common


RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian jessie stable"

RUN apt-get update

RUN apt-get install docker-ce

RUN docker pull tchikladze/chatbot

WORKDIR /src
COPY . /src

RUN rm -rf .env && cp .env.docker.staging .env
RUN npm install
RUN ln -s /src/node_modules/sequelize-cli-typescript/lib/sequelize /usr/local/bin/sequelize
RUN npm run build

RUN npm install -g n

RUN n 8.10.0 

ENV HOST 0.0.0.0
